#!/usr/bin/env bash
#
# Verify that the addresses produced by mnemonic.py match the ones produced
# by the real Electrum daemon for the same mnemonic.
#
# It starts an isolated Electrum daemon (temp datadir, never touches the user's
# wallets), restores each mnemonic generated by mnemonic.py, lists the receiving
# addresses via the daemon RPC and diffs them against the script output.
#
# Usage:
#   ./test_against_electrum.sh
#
# Environment overrides:
#   ELECTRUM_REPO   path to the Electrum source tree (default: ../bal/electrum)
#   NETWORK         mainnet|testnet|signet|regtest (default: mainnet)
#   COUNT           number of addresses to compare (default: 5)
#   BITS            deterministic entropy passed to mnemonic.py (as --bitshex)
#                   for the BIP39 cases (64 hex chars for 24-word BIP39;
#                   default: 256 zero bits)
#   ELECTRUM_BITS   deterministic 256-bit entropy for the Electrum-type cases
#                   (always 256 bits; default: 256 zero bits)
#   BIP39_WORDS     BIP39 word count 12|15|18|21|24 (default: 24); if changed,
#                   BITS must match the corresponding entropy size
#                   (128/160/192/224/256 bits)
#   SLIP39_WORDS    SLIP-39 master secret size in words 12|24 (default: 24)
#   SLIP39_BITS     deterministic entropy for the SLIP-39 cases (default: 32
#                   zero bytes = 256 bits; 16 bytes for 12 words)
#
# Notes:
#   - `--type electrum` mnemonics are imported with the daemon `restore` command.
#   - `--type bip39` mnemonics are NOT supported by the CLI `restore` command
#     (Electrum only supports BIP39 import through the GUI wizard), so the test
#     builds the wallet with Electrum's own wizard code path
#     (electrum_bip39_restore.py) and then loads it into the daemon. The
#     receiving addresses still come from the daemon via `listaddresses`.
#   - `--type slip39` shares go through the same wizard code path
#     (electrum_slip39_restore.py: slip39.recover_ems + from_bip43_rootseed).
#   - Electrum 2FA seeds cannot be restored as single-key wallets (they are
#     2-of-3 multisig with a trusted cosigner server) and are skipped.
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ELECTRUM_REPO="${ELECTRUM_REPO:-$SCRIPT_DIR/../bal/electrum}"
ELECTRUM_BIN="${ELECTRUM_BIN:-$ELECTRUM_REPO/env/bin/electrum}"
ELECTRUM_PYTHON="${ELECTRUM_PYTHON:-$ELECTRUM_REPO/env/bin/python}"
MNEMONIC_PY="${MNEMONIC_PY:-$SCRIPT_DIR/mnemonic.py}"
BIP39_HELPER="$SCRIPT_DIR/electrum_bip39_restore.py"
SLIP39_HELPER="$SCRIPT_DIR/electrum_slip39_restore.py"
NETWORK="${NETWORK:-mainnet}"
COUNT="${COUNT:-5}"
BIP39_WORDS="${BIP39_WORDS:-24}"
SLIP39_WORDS="${SLIP39_WORDS:-24}"
BITS="${BITS:-$(printf '00%.0s' $(seq 1 32))}"
ELECTRUM_BITS="${ELECTRUM_BITS:-$(printf '00%.0s' $(seq 1 32))}"
SLIP39_BITS="${SLIP39_BITS:-$(printf '00%.0s' $(seq 1 32))}"

if [[ ! -x "$ELECTRUM_BIN" ]]; then
    echo "error: Electrum binary not found at $ELECTRUM_BIN (set ELECTRUM_REPO or ELECTRUM_BIN)" >&2
    exit 1
fi
if [[ ! -f "$MNEMONIC_PY" ]]; then
    echo "error: mnemonic.py not found at $MNEMONIC_PY" >&2
    exit 1
fi

case "$NETWORK" in
    mainnet) CHAIN_FLAGS=() ;;
    testnet) CHAIN_FLAGS=(--testnet) ;;
    signet)  CHAIN_FLAGS=(--signet) ;;
    regtest) CHAIN_FLAGS=(--regtest) ;;
    *) echo "error: unknown network '$NETWORK'" >&2; exit 1 ;;
esac

ELDIR="$(mktemp -d)"
WALLETS="$ELDIR/wallets"
mkdir -p "$WALLETS"
PASS=0
FAIL=0

# Run an electrum CLI command against the isolated datadir.
el() {
    ELECTRUMDIR="$ELDIR" "$ELECTRUM_BIN" "${CHAIN_FLAGS[@]}" "$@"
}

cleanup() {
    el stop >/dev/null 2>&1 || true
    # kill any leftover daemon process bound to our datadir
    pkill -f "ELECTRUMDIR=$ELDIR" >/dev/null 2>&1 || true
    rm -rf "$ELDIR"
}
trap cleanup EXIT

# Start the daemon (offline: derivation needs no network) and wait for RPC.
el daemon -d >/dev/null 2>&1 || true
ready=0
for _ in $(seq 1 60); do
    if el version >/dev/null 2>&1; then
        ready=1
        break
    fi
    sleep 1
done
if [[ "$ready" -ne 1 ]]; then
    echo "error: Electrum daemon did not become ready" >&2
    exit 1
fi

# Restore an Electrum-type mnemonic through the daemon and print the first
# COUNT receiving addresses.
electrum_addresses_from_mnemonic() {
    local mnemonic="$1" wallet="$2"
    el restore "$mnemonic" -w "$wallet" >/dev/null
    el load_wallet -w "$wallet" >/dev/null
    el listaddresses --receiving -w "$wallet" | \
        "$ELECTRUM_PYTHON" -c 'import json,sys; print("\n".join(json.load(sys.stdin)[:int(sys.argv[1])]))' "$COUNT"
}

# Report the outcome of a single comparison and update PASS/FAIL counters.
report() {
    local name="$1" expected_file="$2" actual_file="$3"
    if diff -u "$expected_file" "$actual_file" >"$ELDIR/diff.out" 2>&1; then
        PASS=$((PASS + 1))
        echo "PASS: $name"
    else
        FAIL=$((FAIL + 1))
        echo "FAIL: $name"
        sed 's/^/    /' "$ELDIR/diff.out"
    fi
}
BITS_FLAGS=(--bitshex "$BITS")

ELECTRUM_BITS_FLAGS=(--bitshex "$ELECTRUM_BITS")
BIP39_WORDS_FLAGS=(--bip39-words "$BIP39_WORDS")

SLIP39_BITS_FLAGS=(--bitshex "$SLIP39_BITS")
SLIP39_WORDS_FLAGS=(--slip39-words "$SLIP39_WORDS")

# ---------- Electrum-type mnemonics (daemon `restore`) ----------

run_electrum_case() {
    local name="$1" version="$2"
    local out mnemonic
    out="$("$ELECTRUM_PYTHON" "$MNEMONIC_PY" --type electrum --electrum-version "$version" \
        "${ELECTRUM_BITS_FLAGS[@]}" --count "$COUNT" --network "$NETWORK" --wordlist-file "$SCRIPT_DIR/english.txt" 2>/dev/null)"
    mnemonic="$(printf '%s\n' "$out" | sed -n 's/^Mnemonic (Electrum [^)]*): //p')"
    printf '%s\n' "$out" | sed -n 's/^ *[0-9][0-9]*: //p' >"$ELDIR/expected"
    if [[ -z "$mnemonic" ]]; then
        FAIL=$((FAIL + 1))
        echo "FAIL: electrum/$version (could not extract mnemonic from script output)"
        return
    fi
    electrum_addresses_from_mnemonic "$mnemonic" "$WALLETS/electrum_$name" >"$ELDIR/actual"
    report "electrum/$version ($NETWORK)" "$ELDIR/expected" "$ELDIR/actual"
}

run_electrum_case standard standard
run_electrum_case segwit segwit

# ---------- BIP39 mnemonics (wizard code path + daemon load_wallet) ----------

run_bip39_case() {
    local name="$1" derivation="$2"
    local out mnemonic
    out="$("$ELECTRUM_PYTHON" "$MNEMONIC_PY" --type bip39 --bip39-derivation "$name" \
        "${BITS_FLAGS[@]}" "${BIP39_WORDS_FLAGS[@]}" --count "$COUNT" --network "$NETWORK" --wordlist-file "$SCRIPT_DIR/english.txt" 2>/dev/null)"
    mnemonic="$(printf '%s\n' "$out" | sed -n 's/^Mnemonic (BIP39): //p')"
    printf '%s\n' "$out" | sed -n 's/^ *[0-9][0-9]*: //p' >"$ELDIR/expected"
    if [[ -z "$mnemonic" ]]; then
        FAIL=$((FAIL + 1))
        echo "FAIL: bip39/$name (could not extract mnemonic from script output)"
        return
    fi
    local wallet="$WALLETS/bip39_$name"
    ELECTRUMDIR="$ELDIR" "$ELECTRUM_PYTHON" "$BIP39_HELPER" \
        --mnemonic "$mnemonic" \
        --derivation "$derivation" \
        --chain "$NETWORK" \
        --electrum-path "$ELDIR" \
        --wallet "$wallet"
    el load_wallet -w "$wallet" >/dev/null
    el listaddresses --receiving -w "$wallet" | \
        "$ELECTRUM_PYTHON" -c 'import json,sys; print("\n".join(json.load(sys.stdin)[:int(sys.argv[1])]))' "$COUNT" >"$ELDIR/actual"
    report "bip39/$name ($NETWORK)" "$ELDIR/expected" "$ELDIR/actual"
}

if [[ "$NETWORK" == "mainnet" ]]; then
    COIN=0
else
    COIN=1
fi
run_bip39_case bip44 "m/44h/${COIN}h/0h"
run_bip39_case bip49 "m/49h/${COIN}h/0h"
run_bip39_case bip84 "m/84h/${COIN}h/0h"

# ---------- SLIP-39 mnemonics (wizard code path + daemon load_wallet) ----------

run_slip39_case() {
    local name="$1" derivation="$2"
    local out ms shares
    out="$("$ELECTRUM_PYTHON" "$MNEMONIC_PY" --type slip39 --slip39-shares 3 --slip39-threshold 2 \
        "${SLIP39_BITS_FLAGS[@]}" "${SLIP39_WORDS_FLAGS[@]}" \
        --count "$COUNT" --network "$NETWORK" \
        --wordlist-file "$SCRIPT_DIR/english.txt" \
        --slip39-wordlist "$SCRIPT_DIR/slip39_english.txt" 2>/dev/null)"
    ms="$(printf '%s\n' "$out" | sed -n 's/^  Master secret ([^)]*): //p')"
    mapfile -t share_lines < <(printf '%s\n' "$out" | sed -n 's/^  Share [0-9][0-9]*: //p')
    printf '%s\n' "$out" | sed -n 's/^ *[0-9][0-9]*: //p' >"$ELDIR/expected"
    if [[ -z "$ms" || "${#share_lines[@]}" -ne 3 ]]; then
        FAIL=$((FAIL + 1))
        echo "FAIL: slip39/$name (could not parse script output)"
        return
    fi
    local wallet="$WALLETS/slip39_$name"
    ELECTRUMDIR="$ELDIR" "$ELECTRUM_PYTHON" "$SLIP39_HELPER" \
        --mnemonic "${share_lines[0]}" \
        --mnemonic "${share_lines[1]}" \
        --derivation "$derivation" \
        --chain "$NETWORK" \
        --electrum-path "$ELDIR" \
        --wallet "$wallet"
    el load_wallet -w "$wallet" >/dev/null
    el listaddresses --receiving -w "$wallet" | \
        "$ELECTRUM_PYTHON" -c 'import json,sys; print("\n".join(json.load(sys.stdin)[:int(sys.argv[1])]))' "$COUNT" >"$ELDIR/actual"
    report "slip39/$name ($NETWORK)" "$ELDIR/expected" "$ELDIR/actual"
}

run_slip39_case bip84 "m/84h/${COIN}h/0h"

echo
echo "Results: $PASS passed, $FAIL failed"
[[ "$FAIL" -eq 0 ]]
